Table mesonet_data {
  0 TIMESTAMP
  1 RECORD
  2 Ta_2m_Avg
  3 TaMax_2m
  4 TaMin_2m
  5 RH_2m_Avg
  6 RHMax_2m
  7 RHMin_2m
  8 Dp_2m_Avg
  9 DpMax_2m
  10 DpMin_2m
  11 HeatIndex_2m_Avg
  12 HeatIndexMax_2m
  13 WindChill_2m_Avg
  14 WindChillMin_2m
  15 WndAveSpd_3m
  16 WndVecMagAve_3m
  17 WndAveDir_3m
  18 WndAveDirSD_3m
  19 WndMaxSpd5s_3m
  20 WndMax_5sec_Dir_3m
  21 PresAvg_1pnt5m
  22 PresMax_1pnt5m
  23 PresMin_1pnt5m
  24 Solar_2m_Avg
  25 Rain_1m_Tot
  26 Ts_bare_10cm_Avg
  27 TsMax_bare_10cm
  28 TsMin_bare_10cm
}

Table static_forecast {
  0 TIMESTAMP
  1 collection_time
  2 Ta_2m_Avg
  3 TaMax_2m
  4 TaMin_2m
  5 RH_2m_Avg
  6 WndAveSpd_3m
  7 WndAveDir_3m
  8 WndMaxSpd5s_3m
  9 PresAvg_1pnt5m
  10 Rain_1m_Tot
  11 UV_index
  12 Visibility
  13 Clouds
}

Table rolling_forecast {
  0 TIMESTAMP
  1 collection_time
  2 Ta_2m_Avg
  3 TaMax_2m
  4 TaMin_2m
  5 RH_2m_Avg
  6 WndAveSpd_3m
  7 WndAveDir_3m
  8 WndMaxSpd5s_3m
  9 PresAvg_1pnt5m
  10 Rain_1m_Tot
  11 UV_index
  12 Visibility
  13 Clouds
}

Table weather_data {
  0 TIMESTAMP
  1 RECORD
  2 Ta_2m_Avg
  3 TaMax_2m
  4 TaMin_2m
  5 RH_2m_Avg
  6 RHMax_2m
  7 RHMin_2m
  8 Dp_2m_Avg
  9 DpMax_2m
  10 DpMin_2m
  11 HeatIndex_2m_Avg
  12 HeatIndexMax_2m
  13 WindChill_2m_Avg
  14 WindChillMin_2m
  15 WndAveSpd_3m
  16 WndVecMagAve_3m
  17 WndAveDir_3m
  18 WndAveDirSD_3m
  19 WndMaxSpd5s_3m
  20 WndMax_5sec_Dir_3m
  21 PresAvg_1pnt5m
  22 PresMax_1pnt5m
  23 PresMin_1pnt5m
  24 Solar_2m_Avg
  25 Ts_bare_10cm_Avg
  26 TsMax_bare_10cm
  27 TsMin_bare_10cm
  28 Rain_1m_Tot
  29 Ta_2m_Avg_static_forecast
  30 TaMax_2m_static_forecast
  31 TaMin_2m_static_forecast
  32 RH_2m_Avg_static_forecast
  33 WndAveSpd_3m_static_forecast
  34 WndAveDir_3m_static_forecast
  35 WndMaxSpd5s_3m_static_forecast
  36 PresAvg_1pnt5m_static_forecast
  37 Rain_1m_Tot_static_forecast
  38 UV_index_static_forecast
  39 Visibility_static_forecast
  40 Clouds_static_forecast
  41 Ta_2m_Avg_rolling_forecast
  42 TaMax_2m_rolling_forecast
  43 TaMin_2m_rolling_forecast
  44 RH_2m_Avg_rolling_forecast
  45 WndAveSpd_3m_rolling_forecast
  46 WndAveDir_3m_rolling_forecast
  47 WndMaxSpd5s_3m_rolling_forecast
  48 PresAvg_1pnt5m_rolling_forecast
  49 Rain_1m_Tot_rolling_forecast
  50 UV_index_rolling_forecast
  51 Visibility_rolling_forecast
  52 Clouds_rolling_forecast
}

Table plot_5006 {
  0 TIMESTAMP
  1 is_actual
  2 prediction_timestamp
  3 applied_irrigation
  4 TDR5006B10624
  5 TDR5006B10624_pred
  6 SAP5006B1xx24
  7 SAP5006B1xx24_pred
  8 TDR5006B13024
  9 TDR5006B13024_pred
  10 IRT5006B1xx24
  11 IRT5006B1xx24_pred
  12 TDR5006B11824
  13 TDR5006B11824_pred
  14 DEN5006B1xx24
  15 DEN5006B1xx24_pred
  16 TDR5006B14224
  17 TDR5006B14224_pred
  18 cwsi
  19 cwsi_pred
  20 et
  21 et_pred
  22 swsi
  23 swsi_pred
}

Table plot_5010 {
  0 TIMESTAMP
  1 is_actual
  2 prediction_timestamp
  3 applied_irrigation
  4 TDR5010C11824
  5 TDR5010C11824_pred
  6 TDR5010C13024
  7 TDR5010C13024_pred
  8 IRT5010C1xx24
  9 IRT5010C1xx24_pred
  10 TDR5010C10624
  11 TDR5010C10624_pred
  12 SAP5010C1xx24
  13 SAP5010C1xx24_pred
  14 DEN5010C1xx24
  15 DEN5010C1xx24_pred
  16 cwsi
  17 cwsi_pred
  18 et
  19 et_pred
  20 swsi
  21 swsi_pred
}

Table plot_5023 {
  0 TIMESTAMP
  1 is_actual
  2 prediction_timestamp
  3 applied_irrigation
  4 TDR5023A11824
  5 TDR5023A11824_pred
  6 IRT5023A1xx24
  7 IRT5023A1xx24_pred
  8 TDR5023A10624
  9 TDR5023A10624_pred
  10 DEN5023A1xx24
  11 DEN5023A1xx24_pred
  12 TDR5023A13024
  13 TDR5023A13024_pred
  14 TDR5023A14224
  15 TDR5023A14224_pred
  16 SAP5023A1xx24
  17 SAP5023A1xx24_pred
  18 cwsi
  19 cwsi_pred
  20 et
  21 et_pred
  22 swsi
  23 swsi_pred
}
